### ISSUE TITLE
Modules not found, except Pylint

### ISSUE THREAD

**Issue by crswong888** [elarivie/atom-python-linters#3]
# ⓘ Summary

modules: flake8, mypy, and pydocstyle not found error. Pylint working just fine.

# 👣 Reproduction steps

1. Install linters-python for the first time
2. pip3 install -U flake8 mypy pydocstyle pylint
3. Begin writing code

# 🦄 Expected behaviour:

Mess something up and linter errors should appear with the atom linter package

# 🐞 Actual behaviour:

Three big yellow boxes appear on the side saying the aformentioned modules aren't found, with and option to disable them, which I did.

# 📖 Stack trace:

I don't know where to find this

## 📷 Screenshot:

![Screenshot from 2020-04-05 14-42-17](https://user-images.githubusercontent.com/41302548/78509516-ac963880-774b-11ea-97f2-471e61c9571f.png)

## 📁 Relevant data/files:

None

## 💬 Comment:

I've also used the reccomended pip install syntax: `python3 -m pip install -U`, but it made no difference. I am on Ubuntu 18.04, which used both python2 and python3, so you have to use all that extra syntax in the terminal when using python3, for example, `pytest-3`, `pip3 install`, etc., not sure if this makes a difference. But with respect to the way that python modules are installed on my computer and how theyre exectued, etc., there's no difference between the three not found packages and pylint, which works fine, so I'm thinking that this is an actual bug.

Thanks for maintaining this repository, whoever does. Stay safe out there.

**Comment by elarivie** [comment]
Hello @crswong888,

To debug the linting tools installation could you show the output of the following commands:
- python3 --version
- python3 -m flake8 --version
- python3 -m pylint --version
- python3 -m mypy --version
- python3 -m pydocstyle --version

**Comment by elarivie** [comment]
@crswong888 
To further debug your linting tools installation, you can use/adapt the following wrapper script: https://github.com/elarivie/linter-mypy/issues/22#issuecomment-566394497
